# config client 配置文件
spring: 
  profiles: 
    active: 
      - dev

---
# dev 环境
server: 
  port: 8201

spring: 
  profiles: dev
  application: 
    name: micro-config-client-8201

eureka: 
  client: 
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
# test 环境
server: 
  port: 8202

spring: 
  profiles: test
  application: 
    name: micro-config-client-8202

eureka: 
  client: 
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
